<?php

return [
    'AFG' => 'Afganistán',
    'ALB' => 'Albania',
    'GER' => 'Alemania',
    'AND' => 'Andorra',
    'ANG' => 'Angola',
    'AIA?' => 'Anguila',
    'ATA?' => 'Antártida',
    'ANT' => 'Antigua y Barbuda',
    'KSA' => 'Arabia Saudita',
    'ALG' => 'Argelia',
    'ARG' => 'Argentina',
    'ARM' => 'Armenia',
    'ARU' => 'Aruba',
    'AUS' => 'Australia',
    'AUT' => 'Austria',
    'AZE' => 'Azerbaiyán',

    'BAH' => 'Bahamas',
    'BRN' => 'Bahrein',
	'GGY?' => 'Bailía de Guernsey',
    'BAN' => 'Bangladesh',
    'BAR' => 'Barbados',
    'BLR' => 'Belarús',
    'BEL' => 'Bélgica',
    'BIZ' => 'Belice',
    'BEN' => 'Benín',
	'BER' => 'Bermudas',
    'BOL' => 'Bolivia',
    'BIH' => 'Bosnia y Herzegovina',
    'BOT' => 'Botsuana',
    'BRA' => 'Brasil',
    'BRU' => 'Brunei',
    'BUL' => 'Bulgaria',
    'BUR' => 'Burkina Faso',
    'BDI' => 'Burundi',
    'BHU' => 'Bután',

    'CPV' => 'Cabo Verde',
	'CAM' => 'Camboya',
	'CMR' => 'Camerún',
    'CAN' => 'Canadá',
	'BES?' => 'Caribe Neerlandés',
    'CHA' => 'Chad',
    'CZE' => 'Chequia',
    'CHI' => 'Chile',
    'CHN' => 'China',
    'CYP' => 'Chipre',
	'VAT?' => 'Ciudad del Vaticano',
    'COL' => 'Colombia',
    'COM' => 'Comores',
    'PRK' => 'Corea del Norte',
    'KOR' => 'Corea del Sur',
    'CIV' => 'Costa de Marfil',
    'CRC' => 'Costa Rica',
    'CRO' => 'Croacia',
    'CUB' => 'Cuba',
	'CUW?' => 'Curacao',

    'DEN' => 'Dinamarca',
    'DMA' => 'Dominica',

    'ECU' => 'Ecuador',
    'EGY' => 'Egipto',
    'ESA' => 'El Salvador',
    'UAE' => 'Emiratos Árabes Unidos',
    'ERI' => 'Eritrea',
    'SVK' => 'Eslovaquia',
    'SLO' => 'Eslovenia',
    'ESP' => 'España',
	'FSM' => 'Estados Federados de Micronesia',
    'USA' => 'Estados Unidos de América',
    'EST' => 'Estonia',
	'SWZ' => 'Esuatini',
    'ETH' => 'Etiopía',

    'PHI' => 'Filipinas',
    'FIN' => 'Finlandia',
    'FJI' => 'Fiyi',
    'FRA' => 'Francia',

    'GAB' => 'Gabón',
    'GAM' => 'Gambia',
    'GEO' => 'Georgia',
	'SGS?' => 'Georgia del Sur y las Islas Sandwich del Sur',
    'GHA' => 'Ghana',
    'GIB?' => 'Gibraltar',
    'GRN' => 'Granada',
    'GRE' => 'Grecia',
	'GRL?' => 'Groenlandia',
    'GLP?' => 'Guadalupe',
    'GUM' => 'Guam',
    'GUA' => 'Guatemala',
    'GUY' => 'Guayana',
	'GUF?' => 'Guayana Francesa',
	'GUI' => 'Guinea',
	'GEQ' => 'Guinea Ecuatorial',
	'GBS' => 'Guinea-Bissau',

    'HAI' => 'Haití',
	'HON' => 'Honduras',
	'HKG' => 'Hong Kong',
	'HUN' => 'Hungría',

	'IND' => 'India',
	'INA' => 'Indonesia',
	'IRI' => 'Irán',
	'IRQ' => 'Iraq',
	'IRL' => 'Irlanda',
	'BVT?' => 'Isla Bouvet',
	'IMN?' => 'Isla de Man',
    'CXR?' => 'Isla de Navidad',
	'MAF?' => 'Isla de San Martín',
	'MRI' => 'Isla Mauricio',
    'NFK?' => 'Isla Norfolk',
    'ISL' => 'Islandia',
	'ALA?' => 'Islas Aland',
	'CAY' => 'Islas Caimán',
	'CCK?' => 'Islas Cocos',
	'COK' => 'Islas Cook',
	'FRO?' => 'Islas Feroe',
	'HMD?' => 'Islas Heard y Mcdonald',
	'FLK?' => 'Islas Malvinas',
	'MNP?' => 'Islas Marianas del Norte',
	'MHL' => 'Islas Marshall',
	'PCN?' => 'Islas Pitcairn',
	'SOL' => 'Islas Salomón',
	'TCA?' => 'Islas Turcas y Caicos',
	'UMI?' => 'Islas ultramarinas menores de los Estados Unidos',
	'IVB' => 'Islas Vírgenes Británicas',
	'ISV' => 'Islas Vírgenes Americanas',
	'ISR' => 'Israel',
	'ITA' => 'Italia',

	'JAM' => 'Jamaica',
	'JPN' => 'Japón',
	'JEY?' => 'Jersey',
	'JOR' => 'Jordania',

	'KAZ' => 'Kazakhstan',
	'KEN' => 'Kenia',
	'KGZ' => 'Kirguistán',
	'KIR' => 'Kiribati',
	'KOS' => 'Kosovo',
	'KUW' => 'Kuwait',

	'LAO' => 'Laos',
	'LES' => 'Lesotho',
	'LAT' => 'Letonia',
	'LBN' => 'Líbano',
	'LBR' => 'Liberia',
	'LBA' => 'Libia',
	'LIE' => 'Liechtenstein',
	'LTU' => 'Lituania',
	'LUX' => 'Luxemburgo',

	'MAC?' => 'Macao',
	'MKD' => 'Macedonia del Norte',
	'MAD' => 'Madagascar',
	'MAS' => 'Malasia',
	'MAW' => 'Malawi',
	'MDV' => 'Maldivas',
	'MLI' => 'Malí',
	'MLT' => 'Malta',
	'MAR' => 'Marruecos',
	'MTQ?' => 'Martinica',
	'MTN' => 'Mauritania',
	'MYT?' => 'Mayotte',
	'MEX' => 'México',
	'MDA' => 'Moldavia',
	'MGL' => 'Mongolia',
	'MNE' => 'Montenegro',
	'MSR?' => 'Montserrat',
	'MOZ' => 'Mozambique',
	'MYA' => 'Myanmar',

	'NAM' => 'Namibia',
	'NRU' => 'Nauru',
	'NEP' => 'Nepal',
	'NCA' => 'Nicaragua',
	'NIG' => 'Níger',
	'NGR' => 'Nigeria',
	'NIU?' => 'Niue',
	'NOR' => 'Noruega',
	'NCL?' => 'Nueva Caledonia',
	'NZL' => 'Nueva Zelanda',

	'OMA' => 'Omán',

	'NED' => 'Países Bajos',
	'PAK' => 'Pakistán',
	'PLW' => 'Palau',
	'PLE' => 'Palestina',
	'PAN' => 'Panamá',
	'PNG' => 'Papúa Nueva Guinea',
	'PAR' => 'Paraguay',
	'PER' => 'Perú',
	'PYF?' => 'Polinesia Francés',
	'POL' => 'Polonia',
	'POR' => 'Portugal',
	'MON' => 'Principado de Mónaco',
	'PUR' => 'Puerto Rico',

	'QAT' => 'Qatar',

	'GBR' => 'Reino Unido',
	'CAF' => 'República Centroafricana',
	'CGO' => 'República del Congo',
    'COD' => 'República Democrática del Congo',
	'DOM' => 'República Dominicana',
	'REU?' => 'Reunión',
	'RWA' => 'Ruanda',
	'ROU' => 'Rumania',
	'RUS' => 'Rusia',

	'ESH?' => 'Sahara Occidental',
	'SAM' => 'Samoa',
	'ASA' => 'Samoa Americana',
	'BLM?' => 'San Bartolomé',
	'SKN' => 'San Cristóbal y Nieves',
	'SMR' => 'San Marino',
	'SPM?' => 'San Pedro y Miquelón',
	'VIN' => 'San Vicente y las Granadinas',
	'SHN?' => 'Santa Elena, Ascensión y Tristán de Acuña',
	'LCA' => 'Santa Lucía',
	'STP' => 'Santo Tomé y Príncipe',
	'SEN' => 'Senegal',
	'SRB' => 'Serbia',
	'SEY' => 'Seychelles',
	'SLE' => 'Sierra Leona',
	'SGP' => 'Singapur',
	'SXM?' => 'Sint Maarten',
	'SYR' => 'Siria',
	'SOM' => 'Somalia',
	'SRI' => 'Sri Lanka',
	'RSA' => 'Sudáfrica',
	'SUD' => 'Sudán',
	'SSD?' => 'Sudán del Sur',
	'SWE' => 'Suecia',
	'SUI' => 'Suiza',
	'SUR' => 'Surinam',
	'SJM?' => 'Svalbard y Jan Mayen',

	'THA' => 'Tailandia',
	'TPE' => 'Taiwán',
	'TAN' => 'Tanzania',
	'TJK' => 'Tayikistán',
	'IOT?' => 'Territorio Británico del Océano Índico',
	'ATF?' => 'Territorios Australes y Antárticos Franceses',
	'TLS' => 'Timor Oriental',
	'TOG' => 'Togo',
	'TKL?' => 'Tokelau',
	'TGA' => 'Tonga',
	'TTO' => 'Trinidad y Tobago',
	'TUN' => 'Túnez',
	'TKM' => 'Turkmenistán',
	'TUR' => 'Turquía',
	'TUV' => 'Tuvalu',

	'UKR' => 'Ucrania',
	'UGA' => 'Uganda',
	'URU' => 'Uruguay',
	'UZB' => 'Uzbekistán',

	'VAN' => 'Vanuatu',
	'VEN' => 'Venezuela',
	'VIE' => 'Vietnam',

	'WLF?' => 'Wallis y Futuna',

	'YEM' => 'Yemen',
	'DJI' => 'Yibuti',

	'ZAM' => 'Zambia',
	'ZIM' => 'Zimbabue',
];
