<?php

return [
    'AFG' => 'Afganistán',
    'ALB' => 'Albania',
    'DEU' => 'Alemania',
    'AND' => 'Andorra',
    'AGO' => 'Angola',
    'AIA' => 'Anguila',
    'ATA' => 'Antártida',
    'ATG' => 'Antigua y Barbuda',
    'SAU' => 'Arabia Saudita',
    'DZA' => 'Argelia',
    'ARG' => 'Argentina',
    'ARM' => 'Armenia',
    'ABW' => 'Aruba',
    'AUS' => 'Australia',
    'AUT' => 'Austria',
    'AZE' => 'Azerbaiyán',

    'BHS' => 'Bahamas',
    'BHR' => 'Bahrein',
	'GGY' => 'Bailía de Guernsey',
    'BGD' => 'Bangladesh',
    'BRB' => 'Barbados',
    'BLR' => 'Belarús',
    'BEL' => 'Bélgica',
    'BLZ' => 'Belice',
    'BEN' => 'Benín',
	'BMU' => 'Bermudas',
    'BOL' => 'Bolivia',
    'BIH' => 'Bosnia y Herzegovina',
    'BWA' => 'Botsuana',
    'BRA' => 'Brasil',
    'BRN' => 'Brunei',
    'BGR' => 'Bulgaria',
    'BFA' => 'Burkina Faso',
    'BDI' => 'Burundi',
    'BTN' => 'Bután',

    'CPV' => 'Cabo Verde',
	'KHM' => 'Camboya',
	'CMR' => 'Camerún',
    'CAN' => 'Canadá',
	'BES' => 'Caribe Neerlandés',
    'TCD' => 'Chad',
    'CZE' => 'Chequia',
    'CHL' => 'Chile',
    'CHN' => 'China',
    'CYP' => 'Chipre',
	'VAT' => 'Ciudad del Vaticano',
    'COL' => 'Colombia',
    'COM' => 'Comores',
    'PRK' => 'Corea del Norte',
    'KOR' => 'Corea del Sur',
    'CIV' => 'Costa de Marfil',
    'CRI' => 'Costa Rica',
    'HRV' => 'Croacia',
    'CUB' => 'Cuba',
	'CUW' => 'Curacao',

    'DNK' => 'Dinamarca',
    'DMA' => 'Dominica',

    'ECU' => 'Ecuador',
    'EGY' => 'Egipto',
    'SLV' => 'El Salvador',
    'ARE' => 'Emiratos Árabes Unidos',
    'ERI' => 'Eritrea',
    'SVK' => 'Eslovaquia',
    'SVN' => 'Eslovenia',
    'ESP' => 'España',
	'FSM' => 'Estados Federados de Micronesia',
    'USA' => 'Estados Unidos de América',
    'EST' => 'Estonia',
	'SWZ' => 'Esuatini',
    'ETH' => 'Etiopía',

    'PHL' => 'Filipinas',
    'FIN' => 'Finlandia',
    'FJI' => 'Fiyi',
    'FRA' => 'Francia',

    'GAB' => 'Gabón',
    'GMB' => 'Gambia',
    'GEO' => 'Georgia',
	'SGS' => 'Georgia del Sur y las Islas Sandwich del Sur',
    'GHA' => 'Ghana',
    'GIB' => 'Gibraltar',
    'GRD' => 'Granada',
    'GRC' => 'Grecia',
	'GRL' => 'Groenlandia',
    'GLP' => 'Guadalupe',
    'GUM' => 'Guam',
    'GTM' => 'Guatemala',
    'GUY' => 'Guayana',
	'GUF' => 'Guayana Francesa',
	'GIN' => 'Guinea',
	'GNQ' => 'Guinea Ecuatorial',
	'GNB' => 'Guinea-Bissau',

    'HTI' => 'Haití',
	'HND' => 'Honduras',
	'HKG' => 'Hong Kong',
	'HUN' => 'Hungría',

	'IND' => 'India',
	'IDN' => 'Indonesia',
	'IRN' => 'Irán',
	'IRQ' => 'Iraq',
	'IRL' => 'Irlanda',
	'BVT' => 'Isla Bouvet',
	'IMN' => 'Isla de Man',
    'CXR' => 'Isla de Navidad',
	'MAF' => 'Isla de San Martín',
	'MUS' => 'Isla Mauricio',
    'NFK' => 'Isla Norfolk',
    'ISL' => 'Islandia',
	'ALA' => 'Islas Aland',
	'CYM' => 'Islas Caimán',
	'CCK' => 'Islas Cocos',
	'COK' => 'Islas Cook',
	'FRO' => 'Islas Feroe',
	'HMD' => 'Islas Heard y Mcdonald',
	'FLK' => 'Islas Malvinas',
	'MNP' => 'Islas Marianas del Norte',
	'MHL' => 'Islas Marshall',
	'PCN' => 'Islas Pitcairn',
	'SLB' => 'Islas Salomón',
	'TCA' => 'Islas Turcas y Caicos',
	'UMI' => 'Islas ultramarinas menores de los Estados Unidos',
	'VGB' => 'Islas Vírgenes Británicas',
	'VIR' => 'Islas Vírgenes Americanas',
	'ISR' => 'Israel',
	'ITA' => 'Italia',

	'JAM' => 'Jamaica',
	'JPN' => 'Japón',
	'JEY' => 'Jersey',
	'JOR' => 'Jordania',

	'KAZ' => 'Kazakhstan',
	'KEN' => 'Kenia',
	'KGZ' => 'Kirguistán',
	'KIR' => 'Kiribati',
	'XKX' => 'Kosovo',
	'KWT' => 'Kuwait',

	'LAO' => 'Laos',
	'LSO' => 'Lesotho',
	'LVA' => 'Letonia',
	'LBN' => 'Líbano',
	'LBR' => 'Liberia',
	'LBY' => 'Libia',
	'LIE' => 'Liechtenstein',
	'LTU' => 'Lituania',
	'LUX' => 'Luxemburgo',

	'MAC' => 'Macao',
	'MKD' => 'Macedonia del Norte',
	'MDG' => 'Madagascar',
	'MYS' => 'Malasia',
	'MWI' => 'Malawi',
	'MDV' => 'Maldivas',
	'MLI' => 'Malí',
	'MLT' => 'Malta',
	'MAR' => 'Marruecos',
	'MTQ' => 'Martinica',
	'MRT' => 'Mauritania',
	'MYT' => 'Mayotte',
	'MEX' => 'México',
	'MDA' => 'Moldavia',
	'MNG' => 'Mongolia',
	'MNE' => 'Montenegro',
	'MSR' => 'Montserrat',
	'MOZ' => 'Mozambique',
	'MMR' => 'Myanmar',

	'NAM' => 'Namibia',
	'NRU' => 'Nauru',
	'NPL' => 'Nepal',
	'NIC' => 'Nicaragua',
	'NER' => 'Níger',
	'NGA' => 'Nigeria',
	'NIU' => 'Niue',
	'NOR' => 'Noruega',
	'NCL' => 'Nueva Caledonia',
	'NZL' => 'Nueva Zelanda',

	'OMN' => 'Omán',

	'NLD' => 'Países Bajos',
	'PAK' => 'Pakistán',
	'PLW' => 'Palau',
	'PSE' => 'Palestina',
	'PAN' => 'Panamá',
	'PNG' => 'Papúa Nueva Guinea',
	'PRY' => 'Paraguay',
	'PER' => 'Perú',
	'PYF' => 'Polinesia Francés',
	'POL' => 'Polonia',
	'PRT' => 'Portugal',
	'MCO' => 'Principado de Mónaco',
	'PRI' => 'Puerto Rico',

	'QAT' => 'Qatar',

	'GBR' => 'Reino Unido',
	'CAF' => 'República Centroafricana',
	'COG' => 'República del Congo',
    'COD' => 'República Democrática del Congo',
	'DOM' => 'República Dominicana',
	'REU' => 'Reunión',
	'RWA' => 'Ruanda',
	'ROU' => 'Rumania',
	'RUS' => 'Rusia',

	'ESH' => 'Sahara Occidental',
	'WSM' => 'Samoa',
	'ASM' => 'Samoa Americana',
	'BLM' => 'San Bartolomé',
	'KNA' => 'San Cristóbal y Nieves',
	'SMR' => 'San Marino',
	'SPM' => 'San Pedro y Miquelón',
	'VCT' => 'San Vicente y las Granadinas',
	'SHN' => 'Santa Elena, Ascensión y Tristán de Acuña',
	'LCA' => 'Santa Lucía',
	'STP' => 'Santo Tomé y Príncipe',
	'SEN' => 'Senegal',
	'SRB' => 'Serbia',
	'SYC' => 'Seychelles',
	'SLE' => 'Sierra Leona',
	'SGP' => 'Singapur',
	'SXM' => 'Sint Maarten',
	'SYR' => 'Siria',
	'SOM' => 'Somalia',
	'LKA' => 'Sri Lanka',
	'ZAF' => 'Sudáfrica',
	'SDN' => 'Sudán',
	'SSD' => 'Sudán del Sur',
	'SWE' => 'Suecia',
	'CHE' => 'Suiza',
	'SUR' => 'Surinam',
	'SJM' => 'Svalbard y Jan Mayen',

	'THA' => 'Tailandia',
	'TWN' => 'Taiwán',
	'TZA' => 'Tanzania',
	'TJK' => 'Tayikistán',
	'IOT' => 'Territorio Británico del Océano Índico',
	'ATF' => 'Territorios Australes y Antárticos Franceses',
	'TLS' => 'Timor Oriental',
	'TGO' => 'Togo',
	'TKL' => 'Tokelau',
	'TON' => 'Tonga',
	'TTO' => 'Trinidad y Tobago',
	'TUN' => 'Túnez',
	'TKM' => 'Turkmenistán',
	'TUR' => 'Turquía',
	'TUV' => 'Tuvalu',

	'UKR' => 'Ucrania',
	'UGA' => 'Uganda',
	'URY' => 'Uruguay',
	'UZB' => 'Uzbekistán',

	'VUT' => 'Vanuatu',
	'VEN' => 'Venezuela',
	'VNM' => 'Vietnam',

	'WLF' => 'Wallis y Futuna',

	'YEM' => 'Yemen',
	'DJI' => 'Yibuti',

	'ZMB' => 'Zambia',
	'ZWE' => 'Zimbabue',
];
