<?php

return [
    'AF' => 'Afganistán',
    'AL' => 'Albania',
    'GM' => 'Alemania',
    'AN' => 'Andorra',
    'AO' => 'Angola',
    'AV' => 'Anguila',
    'AY' => 'Antártida',
    'AC' => 'Antigua y Barbuda',
    'SA' => 'Arabia Saudita',
    'AG' => 'Argelia',
    'AR' => 'Argentina',
    'AM' => 'Armenia',
    'AA' => 'Aruba',
    'AS' => 'Australia',
    'AU' => 'Austria',
    'AJ' => 'Azerbaiyán',

    'BF' => 'Bahamas',
    'BA' => 'Bahrein',
	'GK' => 'Bailía de Guernsey',
    'BG' => 'Bangladesh',
    'BB' => 'Barbados',
    'BO' => 'Belarús',
    'BE' => 'Bélgica',
    'BH' => 'Belice',
    'BN' => 'Benín',
	'BD' => 'Bermudas',
    'BL' => 'Bolivia',
    'BK' => 'Bosnia y Herzegovina',
    'BC' => 'Botsuana',
    'BR' => 'Brasil',
    'BX' => 'Brunei',
    'BU' => 'Bulgaria',
    'UV' => 'Burkina Faso',
    'BY' => 'Burundi',
    'BT' => 'Bután',

    'CV' => 'Cabo Verde',
	'CB' => 'Camboya',
	'CM' => 'Camerún',
    'CA' => 'Canadá',
	'BES?' => 'Caribe Neerlandés',
    'CD' => 'Chad',
    'EZ' => 'Chequia',
    'CI' => 'Chile',
    'CH' => 'China',
    'CY' => 'Chipre',
	'VT' => 'Ciudad del Vaticano',
    'CO' => 'Colombia',
    'CN' => 'Comores',
    'KN' => 'Corea del Norte',
    'KS' => 'Corea del Sur',
    'IV' => 'Costa de Marfil',
    'CS' => 'Costa Rica',
    'HR' => 'Croacia',
    'CU' => 'Cuba',
	'UC' => 'Curacao',

    'DA' => 'Dinamarca',
    'DO' => 'Dominica',

    'EC' => 'Ecuador',
    'EG' => 'Egipto',
    'ES' => 'El Salvador',
    'AE' => 'Emiratos Árabes Unidos',
    'ER' => 'Eritrea',
    'LO' => 'Eslovaquia',
    'SI' => 'Eslovenia',
    'SP' => 'España',
	'FM' => 'Estados Federados de Micronesia',
    'US' => 'Estados Unidos de América',
    'EN' => 'Estonia',
	'WZ' => 'Esuatini',
    'ET' => 'Etiopía',

    'RP' => 'Filipinas',
    'FI' => 'Finlandia',
    'FJ' => 'Fiyi',
    'FR' => 'Francia',

    'GB' => 'Gabón',
    'GA' => 'Gambia',
    'GG' => 'Georgia',
	'SX' => 'Georgia del Sur y las Islas Sandwich del Sur',
    'GH' => 'Ghana',
    'GI' => 'Gibraltar',
    'GJ' => 'Granada',
    'GR' => 'Grecia',
	'GL' => 'Groenlandia',
    'GP' => 'Guadalupe',
    'GQ' => 'Guam',
    'GT' => 'Guatemala',
    'GY' => 'Guayana',
	'FG' => 'Guayana Francesa',
	'GV' => 'Guinea',
	'EK' => 'Guinea Ecuatorial',
	'PU' => 'Guinea-Bissau',

    'HA' => 'Haití',
	'HO' => 'Honduras',
	'HK' => 'Hong Kong',
	'HU' => 'Hungría',

	'IN' => 'India',
	'ID' => 'Indonesia',
	'IR' => 'Irán',
	'IZ' => 'Iraq',
	'EI' => 'Irlanda',
	'BV' => 'Isla Bouvet',
	'IMN?' => 'Isla de Man',
    'KT' => 'Isla de Navidad',
	'RN' => 'Isla de San Martín',
	'MP' => 'Isla Mauricio',
    'NF' => 'Isla Norfolk',
    'IC' => 'Islandia',
	'ALA?' => 'Islas Aland',
	'CJ' => 'Islas Caimán',
	'CK' => 'Islas Cocos',
	'CW' => 'Islas Cook',
	'FO' => 'Islas Feroe',
	'HM' => 'Islas Heard y Mcdonald',
	'FK' => 'Islas Malvinas',
	'CQ' => 'Islas Marianas del Norte',
	'RM' => 'Islas Marshall',
	'PC' => 'Islas Pitcairn',
	'BP' => 'Islas Salomón',
	'TK' => 'Islas Turcas y Caicos',
	'UM' => 'Islas ultramarinas menores de los Estados Unidos',
	'VI' => 'Islas Vírgenes Británicas',
	'VQ' => 'Islas Vírgenes Americanas',
	'IS' => 'Israel',
	'IT' => 'Italia',

	'JM' => 'Jamaica',
	'JA' => 'Japón',
	'JE' => 'Jersey',
	'JO' => 'Jordania',

	'KZ' => 'Kazakhstan',
	'KE' => 'Kenia',
	'KG' => 'Kirguistán',
	'KR' => 'Kiribati',
	'KV' => 'Kosovo',
	'KU' => 'Kuwait',

	'LA' => 'Laos',
	'LT' => 'Lesotho',
	'LG' => 'Letonia',
	'LE' => 'Líbano',
	'LI' => 'Liberia',
	'LY' => 'Libia',
	'LS' => 'Liechtenstein',
	'LH' => 'Lituania',
	'LU' => 'Luxemburgo',

	'MC' => 'Macao',
	'MK' => 'Macedonia del Norte',
	'MA' => 'Madagascar',
	'MY' => 'Malasia',
	'MI' => 'Malawi',
	'MV' => 'Maldivas',
	'ML' => 'Malí',
	'MT' => 'Malta',
	'MO' => 'Marruecos',
	'MB' => 'Martinica',
	'MR' => 'Mauritania',
	'MF' => 'Mayotte',
	'MX' => 'México',
	'MD' => 'Moldavia',
	'MG' => 'Mongolia',
	'MJ' => 'Montenegro',
	'MH' => 'Montserrat',
	'MZ' => 'Mozambique',
	'BM' => 'Myanmar',

	'WA' => 'Namibia',
	'NR' => 'Nauru',
	'NP' => 'Nepal',
	'NU' => 'Nicaragua',
	'NG' => 'Níger',
	'NI' => 'Nigeria',
	'NE' => 'Niue',
	'NO' => 'Noruega',
	'NC' => 'Nueva Caledonia',
	'NZ' => 'Nueva Zelanda',

	'MU' => 'Omán',

	'NL' => 'Países Bajos',
	'PK' => 'Pakistán',
	'PS' => 'Palau',
	'WE' => 'Palestina',
	'PM' => 'Panamá',
	'PP' => 'Papúa Nueva Guinea',
	'PA' => 'Paraguay',
	'PE' => 'Perú',
	'FP' => 'Polinesia Francés',
	'PL' => 'Polonia',
	'PO' => 'Portugal',
	'MN' => 'Principado de Mónaco',
	'RQ' => 'Puerto Rico',

	'QA' => 'Qatar',

	'UK' => 'Reino Unido',
	'CT' => 'República Centroafricana',
	'CF' => 'República del Congo',
    'CG' => 'República Democrática del Congo',
	'DR' => 'República Dominicana',
	'RE' => 'Reunión',
	'RW' => 'Ruanda',
	'RO' => 'Rumania',
	'RS' => 'Rusia',

	'WI' => 'Sahara Occidental',
	'WS' => 'Samoa',
	'AQ' => 'Samoa Americana',
	'TB' => 'San Bartolomé',
	'SC' => 'San Cristóbal y Nieves',
	'SM' => 'San Marino',
	'SB' => 'San Pedro y Miquelón',
	'VC' => 'San Vicente y las Granadinas',
	'SH' => 'Santa Elena, Ascensión y Tristán de Acuña',
	'ST' => 'Santa Lucía',
	'TP' => 'Santo Tomé y Príncipe',
	'SG' => 'Senegal',
	'RI' => 'Serbia',
	'SE' => 'Seychelles',
	'SL' => 'Sierra Leona',
	'SN' => 'Singapur',
	'NN' => 'Sint Maarten',
	'SY' => 'Siria',
	'SO' => 'Somalia',
	'CE' => 'Sri Lanka',
	'SF' => 'Sudáfrica',
	'SU' => 'Sudán',
	'SSD?' => 'Sudán del Sur',
	'SW' => 'Suecia',
	'SZ' => 'Suiza',
	'NS' => 'Surinam',
	'SV' => 'Svalbard y Jan Mayen',

	'TH' => 'Tailandia',
	'TW' => 'Taiwán',
	'TZ' => 'Tanzania',
	'TI' => 'Tayikistán',
	'IO' => 'Territorio Británico del Océano Índico',
	'FS' => 'Territorios Australes y Antárticos Franceses',
	'TT' => 'Timor Oriental',
	'TO' => 'Togo',
	'TL' => 'Tokelau',
	'TN' => 'Tonga',
	'TD' => 'Trinidad y Tobago',
	'TS' => 'Túnez',
	'TX' => 'Turkmenistán',
	'TU' => 'Turquía',
	'TV' => 'Tuvalu',

	'UP' => 'Ucrania',
	'UG' => 'Uganda',
	'UY' => 'Uruguay',
	'UZ' => 'Uzbekistán',

	'NH' => 'Vanuatu',
	'VE' => 'Venezuela',
	'VM' => 'Vietnam',

	'WF' => 'Wallis y Futuna',

	'YM' => 'Yemen',
	'DJ' => 'Yibuti',

	'ZA' => 'Zambia',
	'ZI' => 'Zimbabue',
];
