<?php

return [
	'AF' => 'Afganistán',
	'AL' => 'Albania',
	'DE' => 'Alemania',
	'AD' => 'Andorra',
	'AO' => 'Angola',
	'AI' => 'Anguila',
	'AQ' => 'Antártida',
	'AG' => 'Antigua y Barbuda',
	'SA' => 'Arabia Saudita',
	'DZ' => 'Argelia',
	'AR' => 'Argentina',
	'AM' => 'Armenia',
	'AW' => 'Aruba',
	'AU' => 'Australia',
	'AT' => 'Austria',
	'AZ' => 'Azerbaiyán',

	'BS' => 'Bahamas',
	'BH' => 'Bahrein',
	'GG' => 'Bailía de Guernsey',
	'BD' => 'Bangladesh',
	'BB' => 'Barbados',
	'BY' => 'Belarús',
	'BE' => 'Bélgica',
	'BZ' => 'Belice',
	'BJ' => 'Benín',
	'BM' => 'Bermudas',
	'BO' => 'Bolivia',
	'BA' => 'Bosnia y Herzegovina',
	'BW' => 'Botsuana',
	'BR' => 'Brasil',
	'BN' => 'Brunei Darussalam',
	'BG' => 'Bulgaria',
	'BF' => 'Burkina Faso',
	'BI' => 'Burundi',
	'BT' => 'Bután',

	'CV' => 'Cabo Verde',
	'KH' => 'Camboya',
	'CM' => 'Camerún',
	'CA' => 'Canadá',
	'BQ' => 'Caribe Neerlandés',
	'TD' => 'Chad',
	'CZ' => 'Chequia',
	'CL' => 'Chile',
	'CN' => 'China',
	'CY' => 'Chipre',
	'VA' => 'Ciudad del Vaticano',
	'CO' => 'Colombia',
	'KM' => 'Comores',
	'KP' => 'Corea del Norte',
	'KR' => 'Corea del Sur',
	'CI' => 'Costa de Marfil',
	'CR' => 'Costa Rica',
	'HR' => 'Croacia',
	'CU' => 'Cuba',
	'CW' => 'Curacao',

	'DK' => 'Dinamarca',
	'DM' => 'Dominica',

	'EC' => 'Ecuador',
	'EG' => 'Egipto',
	'SV' => 'El Salvador',
	'AE' => 'Emiratos Árabes Unidos',
	'ER' => 'Eritrea',
	'SK' => 'Eslovaquia',
	'SI' => 'Eslovenia',
	'ES' => 'España',
	'FM' => 'Estados Federados de Micronesia',
	'US' => 'Estados Unidos de América',
	'EE' => 'Estonia',
	'SZ' => 'Esuatini',
	'ET' => 'Etiopía',

	'PH' => 'Filipinas',
	'FI' => 'Finlandia',
	'FJ' => 'Fiyi',
	'FR' => 'Francia',

	'GA' => 'Gabón',
	'GM' => 'Gambia',
	'GE' => 'Georgia',
	'GS' => 'Georgia del Sur y las Islas Sandwich del Sur',
	'GH' => 'Ghana',
	'GI' => 'Gibraltar',
	'GD' => 'Granada',
	'GR' => 'Grecia',
	'GL' => 'Groenlandia',
	'GP' => 'Guadalupe',
	'GU' => 'Guam',
	'GT' => 'Guatemala',
	'GY' => 'Guayana',
	'GF' => 'Guayana Francesa',
	'GN' => 'Guinea',
	'GQ' => 'Guinea Ecuatorial',
	'GW' => 'Guinea-Bissau',

	'HT' => 'Haití',
	'HN' => 'Honduras',
	'HK' => 'Hong Kong',
	'HU' => 'Hungría',

	'IN' => 'India',
	'ID' => 'Indonesia',
	'IR' => 'Irán',
	'IQ' => 'Iraq',
	'IE' => 'Irlanda',
	'BV' => 'Isla Bouvet',
	'IM' => 'Isla de Man',
	'CX' => 'Isla de Navidad',
	'MF' => 'Isla de San Martín',
	'MU' => 'Isla Mauricio',
	'NF' => 'Isla Norfolk',
	'IS' => 'Islandia',
	'AX' => 'Islas Aland',
	'KY' => 'Islas Caimán',
	'CC' => 'Islas Cocos',
	'CK' => 'Islas Cook',
	'FO' => 'Islas Feroe',
	'HM' => 'Islas Heard y Mcdonald',
	'FK' => 'Islas Malvinas',
	'MP' => 'Islas Marianas del Norte',
	'MH' => 'Islas Marshall',
	'PN' => 'Islas Pitcairn',
	'SB' => 'Islas Salomón',
	'TC' => 'Islas Turcas y Caicos',
	'UM' => 'Islas ultramarinas menores de los Estados Unidos',
	'VG' => 'Islas Vírgenes Británicas',
	'VI' => 'Islas Vírgenes Americanas.',
	'IL' => 'Israel',
	'IT' => 'Italia',

	'JM' => 'Jamaica',
	'JP' => 'Japón',
	'JE' => 'Jersey',
	'JO' => 'Jordania',

	'KZ' => 'Kazakhstan',
	'KE' => 'Kenia',
	'KG' => 'Kirguistán',
	'KI' => 'Kiribati',
	'XK' => 'Kosovo',
	'KW' => 'Kuwait',

	'LA' => 'Laos',
	'LS' => 'Lesotho',
	'LV' => 'Letonia',
	'LB' => 'Líbano',
	'LR' => 'Liberia',
	'LY' => 'Libia',
	'LI' => 'Liechtenstein',
	'LT' => 'Lituania',
	'LU' => 'Luxemburgo',

	'MO' => 'Macao',
	'MK' => 'Macedonia del Norte',
	'MG' => 'Madagascar',
	'MY' => 'Malasia',
	'MW' => 'Malawi',
	'MV' => 'Maldivas',
	'ML' => 'Malí',
	'MT' => 'Malta',
	'MA' => 'Marruecos',
	'MQ' => 'Martinica',
	'MR' => 'Mauritania',
	'YT' => 'Mayotte',
	'MX' => 'México',
	'MD' => 'Moldavia',
	'MN' => 'Mongolia',
	'ME' => 'Montenegro',
	'MS' => 'Montserrat',
	'MZ' => 'Mozambique',
	'MM' => 'Myanmar',

	'NA' => 'Namibia',
	'NR' => 'Nauru',
	'NP' => 'Nepal',
	'NI' => 'Nicaragua',
	'NE' => 'Níger',
	'NG' => 'Nigeria',
	'NU' => 'Niue',
	'NO' => 'Noruega',
	'NC' => 'Nueva Caledonia',
	'NZ' => 'Nueva Zelanda',

	'OM' => 'Omán',

	'NL' => 'Países Bajos',
	'PK' => 'Pakistán',
	'PW' => 'Palau',
	'PS' => 'Palestina',
	'PA' => 'Panamá',
	'PG' => 'Papúa Nueva Guinea',
	'PY' => 'Paraguay',
	'PE' => 'Perú',
	'PF' => 'Polinesia Francés',
	'PL' => 'Polonia',
	'PT' => 'Portugal',
	'MC' => 'Principado de Mónaco',
	'PR' => 'Puerto Rico',

	'QA' => 'Qatar',

	'GB' => 'Reino Unido',
	'CF' => 'República Centroafricana',
	'CG' => 'República Del Congo',
	'CD' => 'República Democrática Del Congo',
	'DO' => 'República Dominicana',
	'RE' => 'Reunión',
	'RW' => 'Ruanda',
	'RO' => 'Rumania',
	'RU' => 'Rusia',

	'EH' => 'Sahara Occidental',
	'WS' => 'Samoa',
	'AS' => 'Samoa Americana',
	'BL' => 'San Bartolomé',
	'KN' => 'San Cristóbal y Nieves',
	'SM' => 'San Marino',
	'PM' => 'San Pedro y Miquelón',
	'VC' => 'San Vicente y las Granadinas',
	'SH' => 'Santa Elena, Ascensión y Tristán de Acuña',
	'LC' => 'Santa Lucía',
	'ST' => 'Santo Tomé y Príncipe',
	'SN' => 'Senegal',
	'RS' => 'Serbia',
	'SC' => 'Seychelles',
	'SL' => 'Sierra Leona',
	'SG' => 'Singapur',
	'SX' => 'Sint Maarten',
	'SY' => 'Siria',
	'SO' => 'Somalia',
	'LK' => 'Sri Lanka',
	'ZA' => 'Sudáfrica',
	'SD' => 'Sudán',
	'SS' => 'Sudán del Sur',
	'SE' => 'Suecia',
	'CH' => 'Suiza',
	'SR' => 'Surinam',
	'SJ' => 'Svalbard y Jan Mayen',

	'TH' => 'Tailandia',
	'TW' => 'Taiwán',
	'TZ' => 'Tanzania',
	'TJ' => 'Tayikistán',
	'IO' => 'Territorio Británico del Océano Índico',
	'TF' => 'Territorios Australes y Antárticos Franceses',
	'TL' => 'Timor Oriental',
	'TG' => 'Togo',
	'TK' => 'Tokelau',
	'TO' => 'Tonga',
	'TT' => 'Trinidad y Tobago',
	'TN' => 'Túnez',
	'TM' => 'Turkmenistán',
	'TR' => 'Turquía',
	'TV' => 'Tuvalu',

	'UA' => 'Ucrania',
	'UG' => 'Uganda',
	'UY' => 'Uruguay',
	'UZ' => 'Uzbekistán',

	'VU' => 'Vanuatu',
	'VE' => 'Venezuela',
	'VN' => 'Vietnam',

	'WF' => 'Wallis y Futuna',

	'YE' => 'Yemen',
	'DJ' => 'Yibuti',

	'ZM' => 'Zambia',
	'ZW' => 'Zimbabue',
];
