<?php

return [
	'af' => 'Afganistán',
	'al' => 'Albania',
	'de' => 'Alemania',
	'ad' => 'Andorra',
	'ao' => 'Angola',
	'ai' => 'Anguila',
	'aq' => 'Antártida',
	'ag' => 'Antigua y Barbuda',
	'sa' => 'Arabia Saudita',
	'dz' => 'Argelia',
	'ar' => 'Argentina',
	'am' => 'Armenia',
	'aw' => 'Aruba',
	'au' => 'Australia',
	'at' => 'Austria',
	'az' => 'Azerbaiyán',

	'bs' => 'Bahamas',
	'bh' => 'Bahrein',
	'gg' => 'Bailía de Guernsey',
	'bd' => 'Bangladesh',
	'bb' => 'Barbados',
	'by' => 'Belarús',
	'be' => 'Bélgica',
	'bz' => 'Belice',
	'bj' => 'Benín',
	'bm' => 'Bermudas',
	'bo' => 'Bolivia',
	'ba' => 'Bosnia y Herzegovina',
	'bw' => 'Botsuana',
	'br' => 'Brasil',
	'bn' => 'Brunei',
	'bg' => 'Bulgaria',
	'bf' => 'Burkina Faso',
	'bi' => 'Burundi',
	'bt' => 'Bután',

	'cv' => 'Cabo Verde',
	'kh' => 'Camboya',
	'cm' => 'Camerún',
	'ca' => 'Canadá',
	'bq' => 'Caribe Neerlandés',
	'td' => 'Chad',
	'cz' => 'Chequia',
	'cl' => 'Chile',
	'cn' => 'China',
	'cy' => 'Chipre',
	'va' => 'Ciudad del Vaticano',
	'co' => 'Colombia',
	'km' => 'Comores',
	'kp' => 'Corea del Norte',
	'kr' => 'Corea del Sur',
	'ci' => 'Costa de Marfil',
	'cr' => 'Costa Rica',
	'hr' => 'Croacia',
	'cu' => 'Cuba',
	'cw' => 'Curacao',

	'dk' => 'Dinamarca',
	'dm' => 'Dominica',

	'ec' => 'Ecuador',
	'eg' => 'Egipto',
	'sv' => 'El Salvador',
	'ae' => 'Emiratos Árabes Unidos',
	'er' => 'Eritrea',
	'sk' => 'Eslovaquia',
	'si' => 'Eslovenia',
	'es' => 'España',
	'fm' => 'Estados Federados de Micronesia',
	'us' => 'Estados Unidos de América',
	'ee' => 'Estonia',
	'sz' => 'Esuatini',
	'et' => 'Etiopía',

	'ph' => 'Filipinas',
	'fi' => 'Finlandia',
	'fj' => 'Fiyi',
	'fr' => 'Francia',

	'ga' => 'Gabón',
	'gm' => 'Gambia',
	'ge' => 'Georgia',
	'gs' => 'Georgia del Sur y las Islas Sandwich del Sur',
	'gh' => 'Ghana',
	'gi' => 'Gibraltar',
	'gd' => 'Granada',
	'gr' => 'Grecia',
	'gl' => 'Groenlandia',
	'gp' => 'Guadalupe',
	'gu' => 'Guam',
	'gt' => 'Guatemala',
	'gy' => 'Guayana',
	'gf' => 'Guayana Francesa',
	'gn' => 'Guinea',
	'gq' => 'Guinea Ecuatorial',
	'gw' => 'Guinea-Bissau',

	'ht' => 'Haití',
	'hn' => 'Honduras',
	'hk' => 'Hong Kong',
	'hu' => 'Hungría',

	'in' => 'India',
	'id' => 'Indonesia',
	'ir' => 'Irán',
	'iq' => 'Iraq',
	'ie' => 'Irlanda',
	'bv' => 'Isla Bouvet',
	'im' => 'Isla de Man',
	'cx' => 'Isla de Navidad',
	'mf' => 'Isla de San Martín',
	'mu' => 'Isla Mauricio',
	'nf' => 'Isla Norfolk',
	'is' => 'Islandia',
	'ax' => 'Islas Aland',
	'ky' => 'Islas Caimán',
	'cc' => 'Islas Cocos',
	'ck' => 'Islas Cook',
	'fo' => 'Islas Feroe',
	'hm' => 'Islas Heard y Mcdonald',
	'fk' => 'Islas Malvinas',
	'mp' => 'Islas Marianas del Norte',
	'mh' => 'Islas Marshall',
	'pn' => 'Islas Pitcairn',
	'sb' => 'Islas Salomón',
	'tc' => 'Islas Turcas y Caicos',
	'us' => 'Islas ultramarinas menores de los Estados Unidos',
	'vg' => 'Islas Vírgenes Británicas',
	'vi' => 'Islas Vírgenes Americanas',
	'il' => 'Israel',
	'it' => 'Italia',

	'jm' => 'Jamaica',
	'jp' => 'Japón',
	'je' => 'Jersey',
	'jo' => 'Jordania',

	'kz' => 'Kazakhstan',
	'ke' => 'Kenia',
	'kg' => 'Kirguistán',
	'ki' => 'Kiribati',
	'ko' => 'Kosovo',
	'kw' => 'Kuwait',

	'la' => 'Laos',
	'ls' => 'Lesotho',
	'lv' => 'Letonia',
	'lb' => 'Líbano',
	'lr' => 'Liberia',
	'ly' => 'Libia',
	'li' => 'Liechtenstein',
	'lt' => 'Lituania',
	'lu' => 'Luxemburgo',

	'mo' => 'Macao',
	'mk' => 'Macedonia del Norte',
	'mg' => 'Madagascar',
	'my' => 'Malasia',
	'mw' => 'Malawi',
	'mv' => 'Maldivas',
	'ml' => 'Malí',
	'mt' => 'Malta',
	'ma' => 'Marruecos',
	'mq' => 'Martinica',
	'mr' => 'Mauritania',
	'yt' => 'Mayotte',
	'mx' => 'México',
	'md' => 'Moldavia',
	'mn' => 'Mongolia',
	'me' => 'Montenegro',
	'ms' => 'Montserrat',
	'mz' => 'Mozambique',
	'mm' => 'Myanmar',

	'na' => 'Namibia',
	'nr' => 'Nauru',
	'np' => 'Nepal',
	'ni' => 'Nicaragua',
	'ne' => 'Níger',
	'ng' => 'Nigeria',
	'nu' => 'Niue',
	'no' => 'Noruega',
	'nc' => 'Nueva Caledonia',
	'nz' => 'Nueva Zelanda',

	'om' => 'Omán',

	'nl' => 'Países Bajos',
	'pk' => 'Pakistán',
	'pw' => 'Palau',
	'ps' => 'Palestina',
	'pa' => 'Panamá',
	'pg' => 'Papúa Nueva Guinea',
	'py' => 'Paraguay',
	'pe' => 'Perú',
	'pf' => 'Polinesia Francés',
	'pl' => 'Polonia',
	'pt' => 'Portugal',
	'mc' => 'Principado de Mónaco',
	'pr' => 'Puerto Rico',

	'qa' => 'Qatar',

	'uk' => 'Reino Unido',
	'cf' => 'República Centroafricana',
	'cg' => 'República del Congo',
	'cd' => 'República Democrática del Congo',
	'do' => 'República Dominicana',
	're' => 'Reunión',
	'rw' => 'Ruanda',
	'ro' => 'Rumania',
	'ru' => 'Rusia',

	'eh' => 'Sahara Occidental',
	'ws' => 'Samoa',
	'as' => 'Samoa Americana',
	'bl' => 'San Bartolomé',
	'kn' => 'San Cristóbal y Nieves',
	'sm' => 'San Marino',
	'pm' => 'San Pedro y Miquelón',
	'vc' => 'San Vicente y las Granadinas',
	'sh' => 'Santa Elena, Ascensión y Tristán de Acuña',
	'lc' => 'Santa Lucía',
	'st' => 'Santo Tomé y Príncipe',
	'sn' => 'Senegal',
	'rs' => 'Serbia',
	'sc' => 'Seychelles',
	'sl' => 'Sierra Leona',
	'sg' => 'Singapur',
	'sx' => 'Sint Maarten',
	'sy' => 'Siria',
	'so' => 'Somalia',
	'lk' => 'Sri Lanka',
	'za' => 'Sudáfrica',
	'sd' => 'Sudán',
	'ss' => 'Sudán del Sur',
	'se' => 'Suecia',
	'ch' => 'Suiza',
	'sr' => 'Surinam',
	'sj' => 'Svalbard y Jan Mayen',

	'th' => 'Tailandia',
	'tw' => 'Taiwán',
	'tz' => 'Tanzania',
	'tj' => 'Tayikistán',
	'io' => 'Territorio Británico del Océano Índico',
	'tf' => 'Territorios Australes y Antárticos Franceses',
	'tl' => 'Timor Oriental',
	'tg' => 'Togo',
	'tk' => 'Tokelau',
	'to' => 'Tonga',
	'tt' => 'Trinidad y Tobago',
	'tn' => 'Túnez',
	'tm' => 'Turkmenistán',
	'tr' => 'Turquía',
	'tv' => 'Tuvalu',

	'ua' => 'Ucrania',
	'ug' => 'Uganda',
	'uy' => 'Uruguay',
	'uz' => 'Uzbekistán',

	'vu' => 'Vanuatu',
	've' => 'Venezuela',
	'vn' => 'Vietnam',

	'wf' => 'Wallis y Futuna',

	'ye' => 'Yemen',
	'dj' => 'Yibuti',

	'zm' => 'Zambia',
	'zw' => 'Zimbabue',
];
